/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Thu Dec 22 00:43:58 2016. */

#ifndef PB_COMMAND_SF_PB_H_INCLUDED
#define PB_COMMAND_SF_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Command_CommandType {
    Command_CommandType_PING = 0,
    Command_CommandType_READ = 1,
    Command_CommandType_READ_ALL = 2,
    Command_CommandType_NOTIFICATION = 3
} Command_CommandType;
#define _Command_CommandType_MIN Command_CommandType_PING
#define _Command_CommandType_MAX Command_CommandType_NOTIFICATION
#define _Command_CommandType_ARRAYSIZE ((Command_CommandType)(Command_CommandType_NOTIFICATION+1))

typedef enum _Notification_NotificationType {
    Notification_NotificationType_NONE = 0,
    Notification_NotificationType_PING = 1,
    Notification_NotificationType_ONLINE = 2,
    Notification_NotificationType_NEW_DATA = 3
} Notification_NotificationType;
#define _Notification_NotificationType_MIN Notification_NotificationType_NONE
#define _Notification_NotificationType_MAX Notification_NotificationType_NEW_DATA
#define _Notification_NotificationType_ARRAYSIZE ((Notification_NotificationType)(Notification_NotificationType_NEW_DATA+1))

/* Struct definitions */
typedef struct _SensorName {
    pb_callback_t name;
/* @@protoc_insertion_point(struct:SensorName) */
} SensorName;

typedef struct _SensorRead {
    pb_callback_t name;
    pb_callback_t values;
/* @@protoc_insertion_point(struct:SensorRead) */
} SensorRead;

typedef struct _SensorReadList {
    pb_callback_t reads;
/* @@protoc_insertion_point(struct:SensorReadList) */
} SensorReadList;

typedef struct _Command {
    Command_CommandType command;
/* @@protoc_insertion_point(struct:Command) */
} Command;

typedef struct _Notification {
    Notification_NotificationType what;
/* @@protoc_insertion_point(struct:Notification) */
} Notification;

typedef struct _Ping {
    int32_t value;
/* @@protoc_insertion_point(struct:Ping) */
} Ping;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Command_init_default                     {(Command_CommandType)0}
#define SensorRead_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}}
#define SensorName_init_default                  {{{NULL}, NULL}}
#define Ping_init_default                        {0}
#define SensorReadList_init_default              {{{NULL}, NULL}}
#define Notification_init_default                {(Notification_NotificationType)0}
#define Command_init_zero                        {(Command_CommandType)0}
#define SensorRead_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}}
#define SensorName_init_zero                     {{{NULL}, NULL}}
#define Ping_init_zero                           {0}
#define SensorReadList_init_zero                 {{{NULL}, NULL}}
#define Notification_init_zero                   {(Notification_NotificationType)0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorName_name_tag                      1
#define SensorRead_name_tag                      1
#define SensorRead_values_tag                    2
#define SensorReadList_reads_tag                 1
#define Command_command_tag                      1
#define Notification_what_tag                    1
#define Ping_value_tag                           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Command_fields[2];
extern const pb_field_t SensorRead_fields[3];
extern const pb_field_t SensorName_fields[2];
extern const pb_field_t Ping_fields[2];
extern const pb_field_t SensorReadList_fields[2];
extern const pb_field_t Notification_fields[2];

/* Maximum encoded size of messages (where known) */
#define Command_size                             2
/* SensorRead_size depends on runtime parameters */
/* SensorName_size depends on runtime parameters */
#define Ping_size                                11
/* SensorReadList_size depends on runtime parameters */
#define Notification_size                        2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define COMMAND_SF_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
